
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author richa
 */
public class Liga_Espanola extends javax.swing.JFrame {

    ArrayList<Jugadores> jugtotal = new ArrayList();
    ArrayList<Equipos> equipost = new ArrayList();

    public Liga_Espanola() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar_Jugadores = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        tf_nombrej = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_atacante = new javax.swing.JRadioButton();
        rb_mediocampo = new javax.swing.JRadioButton();
        rb_defensa = new javax.swing.JRadioButton();
        rb_portero = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        tf_habilidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_Disp = new javax.swing.JTextField();
        jb_Guardarjugadores = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tf_tecnica = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_resist = new javax.swing.JTextField();
        bg_posicion = new javax.swing.ButtonGroup();
        Agregar_Equpos = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_nombreequipo = new javax.swing.JTextField();
        tf_presupuesto = new javax.swing.JTextField();
        tf_copas = new javax.swing.JTextField();
        tf_nombreestadio = new javax.swing.JTextField();
        jb_guardarEquipo = new javax.swing.JButton();
        ModificarJugadores = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        rb_portero1 = new javax.swing.JRadioButton();
        tf_resist1 = new javax.swing.JTextField();
        tf_nombrejmod = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_habilidad1 = new javax.swing.JTextField();
        tf_precio1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_Disp1 = new javax.swing.JTextField();
        jb_modificarJugadores = new javax.swing.JButton();
        rb_atacante1 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        rb_mediocampo1 = new javax.swing.JRadioButton();
        tf_tecnica1 = new javax.swing.JTextField();
        rb_defensa1 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        ModificarEquipos = new javax.swing.JDialog();
        tf_copas1 = new javax.swing.JTextField();
        tf_nombreestadio1 = new javax.swing.JTextField();
        jb_ModEquipos = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tf_nombreequipo1 = new javax.swing.JTextField();
        tf_presupuesto1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        popuparbol = new javax.swing.JPopupMenu();
        Ver_Jugador = new javax.swing.JMenuItem();
        Eliminar_jugador = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jb_agregar = new javax.swing.JButton();
        jb_agregarEquipos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaEquipos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaJugadores = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_Distrub = new javax.swing.JTree();
        jLabel17 = new javax.swing.JLabel();
        jb_agregaralarbol = new javax.swing.JButton();
        Eliminarlistadejugadores = new javax.swing.JButton();
        Eliminarlistadeequipos = new javax.swing.JButton();

        jLabel2.setText("Nombre");

        jLabel4.setText("Precio");

        jLabel5.setText("Posicion");

        bg_posicion.add(rb_atacante);
        rb_atacante.setText("Atacante");

        bg_posicion.add(rb_mediocampo);
        rb_mediocampo.setText("Mediocampista");

        bg_posicion.add(rb_defensa);
        rb_defensa.setText("Defensa");

        bg_posicion.add(rb_portero);
        rb_portero.setText("Portero");

        jLabel6.setText("Habilidad");

        jLabel7.setText("Disponibilidad");

        jb_Guardarjugadores.setText("Guardar");
        jb_Guardarjugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_GuardarjugadoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_GuardarjugadoresMouseEntered(evt);
            }
        });

        jLabel8.setText("Tecnica");

        jLabel9.setText("Resistencia");

        javax.swing.GroupLayout Agregar_JugadoresLayout = new javax.swing.GroupLayout(Agregar_Jugadores.getContentPane());
        Agregar_Jugadores.getContentPane().setLayout(Agregar_JugadoresLayout);
        Agregar_JugadoresLayout.setHorizontalGroup(
            Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_JugadoresLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_portero)
                    .addComponent(rb_defensa)
                    .addGroup(Agregar_JugadoresLayout.createSequentialGroup()
                        .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb_atacante)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombrej, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Agregar_JugadoresLayout.createSequentialGroup()
                                .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Agregar_JugadoresLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_habilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Agregar_JugadoresLayout.createSequentialGroup()
                                        .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel8)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_Disp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_tecnica, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_resist, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addComponent(rb_mediocampo))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Agregar_JugadoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_Guardarjugadores)
                .addGap(75, 75, 75))
        );
        Agregar_JugadoresLayout.setVerticalGroup(
            Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_JugadoresLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombrej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tf_habilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Agregar_JugadoresLayout.createSequentialGroup()
                        .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Agregar_JugadoresLayout.createSequentialGroup()
                                .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Agregar_JugadoresLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_atacante))
                                    .addGroup(Agregar_JugadoresLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(tf_Disp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_mediocampo))
                            .addGroup(Agregar_JugadoresLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(tf_tecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_defensa))
                    .addGroup(Agregar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(tf_resist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_portero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jb_Guardarjugadores)
                .addGap(41, 41, 41))
        );

        jLabel10.setText("Agregar Equipos");

        jLabel11.setText("Nombre");

        jLabel12.setText("Presupuesto");

        jLabel13.setText("Copas");

        jLabel14.setText("Estadio");

        jb_guardarEquipo.setText("Guardar Equipo");
        jb_guardarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarEquipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Agregar_EquposLayout = new javax.swing.GroupLayout(Agregar_Equpos.getContentPane());
        Agregar_Equpos.getContentPane().setLayout(Agregar_EquposLayout);
        Agregar_EquposLayout.setHorizontalGroup(
            Agregar_EquposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_EquposLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(Agregar_EquposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(45, 45, 45)
                .addGroup(Agregar_EquposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(Agregar_EquposLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(Agregar_EquposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreequipo)
                            .addComponent(tf_presupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(tf_copas)
                            .addComponent(tf_nombreestadio))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Agregar_EquposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_guardarEquipo)
                .addGap(36, 36, 36))
        );
        Agregar_EquposLayout.setVerticalGroup(
            Agregar_EquposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_EquposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(Agregar_EquposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_nombreequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Agregar_EquposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(tf_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Agregar_EquposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(tf_copas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Agregar_EquposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_nombreestadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jb_guardarEquipo)
                .addGap(28, 28, 28))
        );

        jLabel18.setText("Nombre");

        bg_posicion.add(rb_portero1);
        rb_portero1.setText("Portero");

        jLabel19.setText("Habilidad");

        jLabel20.setText("Precio");

        jLabel21.setText("Disponibilidad");

        jLabel22.setText("Posicion");

        jb_modificarJugadores.setText("Guardar");
        jb_modificarJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarJugadoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_modificarJugadoresMouseEntered(evt);
            }
        });

        bg_posicion.add(rb_atacante1);
        rb_atacante1.setText("Atacante");

        jLabel23.setText("Tecnica");

        bg_posicion.add(rb_mediocampo1);
        rb_mediocampo1.setText("Mediocampista");

        bg_posicion.add(rb_defensa1);
        rb_defensa1.setText("Defensa");

        jLabel24.setText("Resistencia");

        javax.swing.GroupLayout ModificarJugadoresLayout = new javax.swing.GroupLayout(ModificarJugadores.getContentPane());
        ModificarJugadores.getContentPane().setLayout(ModificarJugadoresLayout);
        ModificarJugadoresLayout.setHorizontalGroup(
            ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
            .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarJugadoresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ModificarJugadoresLayout.createSequentialGroup()
                            .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb_portero1)
                                .addComponent(rb_defensa1)
                                .addGroup(ModificarJugadoresLayout.createSequentialGroup()
                                    .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel18)
                                        .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb_atacante1)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel20)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_nombrejmod, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(ModificarJugadoresLayout.createSequentialGroup()
                                            .addComponent(tf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(95, 95, 95)
                                            .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(ModificarJugadoresLayout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(tf_habilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(ModificarJugadoresLayout.createSequentialGroup()
                                                    .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel21)
                                                        .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel24)
                                                            .addComponent(jLabel23)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tf_Disp1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tf_tecnica1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tf_resist1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addComponent(rb_mediocampo1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarJugadoresLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_modificarJugadores)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        ModificarJugadoresLayout.setVerticalGroup(
            ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarJugadoresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(tf_nombrejmod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(tf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(tf_habilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ModificarJugadoresLayout.createSequentialGroup()
                            .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(ModificarJugadoresLayout.createSequentialGroup()
                                    .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ModificarJugadoresLayout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rb_atacante1))
                                        .addGroup(ModificarJugadoresLayout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel21)
                                                .addComponent(tf_Disp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rb_mediocampo1))
                                .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(tf_tecnica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rb_defensa1))
                        .addGroup(ModificarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(tf_resist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(rb_portero1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                    .addComponent(jb_modificarJugadores)
                    .addContainerGap()))
        );

        jb_ModEquipos.setText("Guardar Equipo");
        jb_ModEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ModEquiposMouseClicked(evt);
            }
        });

        jLabel25.setText("Nombre");

        jLabel26.setText("Presupuesto");

        jLabel27.setText("Copas");

        jLabel28.setText("Estadio");

        jLabel29.setText("Modificar Equipos");

        javax.swing.GroupLayout ModificarEquiposLayout = new javax.swing.GroupLayout(ModificarEquipos.getContentPane());
        ModificarEquipos.getContentPane().setLayout(ModificarEquiposLayout);
        ModificarEquiposLayout.setHorizontalGroup(
            ModificarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarEquiposLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel29)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(ModificarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarEquiposLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addGroup(ModificarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ModificarEquiposLayout.createSequentialGroup()
                            .addGroup(ModificarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(jLabel25)
                                .addComponent(jLabel27)
                                .addComponent(jLabel28))
                            .addGap(55, 55, 55)
                            .addGroup(ModificarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombreequipo1)
                                .addComponent(tf_presupuesto1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(tf_copas1)
                                .addComponent(tf_nombreestadio1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarEquiposLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_ModEquipos)))
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
        ModificarEquiposLayout.setVerticalGroup(
            ModificarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(ModificarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarEquiposLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(ModificarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(tf_nombreequipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(ModificarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel26)
                        .addComponent(tf_presupuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(ModificarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel27)
                        .addComponent(tf_copas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(ModificarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(tf_nombreestadio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                    .addComponent(jb_ModEquipos)
                    .addGap(36, 36, 36)))
        );

        Ver_Jugador.setText("Ver Jugador");
        Ver_Jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_JugadorActionPerformed(evt);
            }
        });
        popuparbol.add(Ver_Jugador);

        Eliminar_jugador.setText("Eliminar Jugador");
        popuparbol.add(Eliminar_jugador);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("LIGA ESPANOLA");

        jb_agregar.setText("Agregar Jugador");
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });
        jb_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarActionPerformed(evt);
            }
        });

        jb_agregarEquipos.setText("Agregar Equipo");
        jb_agregarEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarEquiposMouseClicked(evt);
            }
        });

        ListaEquipos.setModel(new DefaultListModel());
        ListaEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaEquiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaEquipos);

        ListaJugadores.setModel(new DefaultListModel());
        ListaJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaJugadoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListaJugadores);

        jLabel15.setText("Equipos");

        jLabel16.setText("Jugadores");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Liga Espanola");
        jt_Distrub.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_Distrub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_DistrubMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_Distrub);

        jLabel17.setText("Distribucion");

        jb_agregaralarbol.setText("Agregar");
        jb_agregaralarbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregaralarbolMouseClicked(evt);
            }
        });

        Eliminarlistadejugadores.setText("Eliminar");
        Eliminarlistadejugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarlistadejugadoresMouseClicked(evt);
            }
        });

        Eliminarlistadeequipos.setText("Eliminar");
        Eliminarlistadeequipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarlistadeequiposMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel15)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_agregarEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(128, 128, 128))))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Eliminarlistadeequipos)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Eliminarlistadejugadores)
                    .addComponent(jb_agregaralarbol))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_agregaralarbol)
                    .addComponent(Eliminarlistadeequipos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Eliminarlistadejugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_agregarEquipos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_agregar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//////AGREGAR JUGADORES BOTON///////////////////
    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        Agregar_Jugadores.setModal(true);
        Agregar_Jugadores.pack();
        Agregar_Jugadores.setLocationRelativeTo(this);
        Agregar_Jugadores.setVisible(true);

    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jb_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_agregarActionPerformed
/////GUARDAR JUGADORES//////////////////
    private void jb_GuardarjugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_GuardarjugadoresMouseClicked
        DefaultListModel modeloj = (DefaultListModel) ListaJugadores.getModel();
        if (rb_atacante.isSelected()) {
            modeloj.addElement(new Jugadores(tf_nombrej.getText(), Integer.parseInt(tf_precio.getText()), "Atacante", tf_Disp.getText(), Double.parseDouble(tf_habilidad.getText()), Double.parseDouble(tf_tecnica.getText()), Double.parseDouble(tf_resist.getText())));
        }
        if (rb_defensa.isSelected()) {
            modeloj.addElement(new Jugadores(tf_nombrej.getText(), Integer.parseInt(tf_precio.getText()), "Defensa", tf_Disp.getText(), Double.parseDouble(tf_habilidad.getText()), Double.parseDouble(tf_tecnica.getText()), Double.parseDouble(tf_resist.getText())));
        }
        if (rb_mediocampo.isSelected()) {
            modeloj.addElement(new Jugadores(tf_nombrej.getText(), Integer.parseInt(tf_precio.getText()), "Medio Campista", tf_Disp.getText(), Double.parseDouble(tf_habilidad.getText()), Double.parseDouble(tf_tecnica.getText()), Double.parseDouble(tf_resist.getText())));
        }
        if (rb_portero.isSelected()) {
            modeloj.addElement(new Jugadores(tf_nombrej.getText(), Integer.parseInt(tf_precio.getText()), "Portero", tf_Disp.getText(), Double.parseDouble(tf_habilidad.getText()), Double.parseDouble(tf_tecnica.getText()), Double.parseDouble(tf_resist.getText())));
        }
        tf_nombrej.setText("");
        tf_precio.setText("");
        tf_Disp.setText("");
        tf_habilidad.setText("");
        tf_tecnica.setText("");
        tf_resist.setText("");


    }//GEN-LAST:event_jb_GuardarjugadoresMouseClicked
/////////////GUARDAR EUIPOS////////////////////////////
    private void jb_guardarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarEquipoMouseClicked

        DefaultListModel modelol = (DefaultListModel) ListaEquipos.getModel();
        modelol.addElement(new Equipos(tf_nombreequipo.getText(), Integer.parseInt(tf_presupuesto.getText()), Integer.parseInt(tf_copas.getText()), tf_nombreestadio.getText()));
        DefaultTreeModel m = (DefaultTreeModel) jt_Distrub.getModel();
        DefaultMutableTreeNode LigaEspanola = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode Equipo;
        Equipo = new DefaultMutableTreeNode(new Equipos(tf_nombreequipo.getText(), Integer.parseInt(tf_presupuesto.getText()), Integer.parseInt(tf_copas.getText()), tf_nombreestadio.getText()));
        LigaEspanola.add(Equipo);
        m.reload();
        tf_nombreestadio.setText("");
        tf_presupuesto.setText("");
        tf_copas.setText("");
        tf_nombreestadio.setText("");


    }//GEN-LAST:event_jb_guardarEquipoMouseClicked

    private void jb_agregarEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarEquiposMouseClicked
        Agregar_Equpos.setModal(true);
        Agregar_Equpos.pack();
        Agregar_Equpos.setLocationRelativeTo(this);
        Agregar_Equpos.setVisible(true);
    }//GEN-LAST:event_jb_agregarEquiposMouseClicked
/////////////METER AL ARBOL /////////////////
    private void jb_agregaralarbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregaralarbolMouseClicked
        if (ListaEquipos.getSelectedIndex() >= 0) {
            if (ListaJugadores.getSelectedIndex() >= 0) {
                DefaultTreeModel modeloarbol = (DefaultTreeModel) jt_Distrub.getModel();
                DefaultMutableTreeNode LigaEspanola = (DefaultMutableTreeNode) modeloarbol.getRoot();

                DefaultListModel modelolista1 = (DefaultListModel) ListaEquipos.getModel();
                DefaultListModel modelolista2 = (DefaultListModel) ListaJugadores.getModel();
                Equipos e = (Equipos) modelolista1.get(ListaEquipos.getSelectedIndex());
                Jugadores j = (Jugadores) modelolista2.get(ListaJugadores.getSelectedIndex());
                String nombre, pos, disp;
                int precioj;
                double hab, tec, res;
                String nombreq;
                int presu;
                int copas;
                String estadio;
                //jugadores
                nombre = j.getNombre();
                pos = j.getPos();
                disp = j.getDisponibilidad();
                precioj = j.getPrecio();
                hab = j.getHabilidad();
                tec = j.getTecnica();
                res = j.getResistencia();
                DefaultMutableTreeNode a = new DefaultMutableTreeNode(new Jugadores(nombre, precioj, pos, disp, hab, tec, res));
                //equipos
                nombreq = e.getNombre();
                presu = e.getPresupuesto();
                copas = e.getCopasgan();
                estadio = e.getEstadio();

                DefaultMutableTreeNode b = new DefaultMutableTreeNode(new Equipos(nombreq, presu, copas, estadio));
                LigaEspanola.removeAllChildren();
                LigaEspanola.add(b);
                b.add(a);
                modeloarbol.reload();

            }

        }

    }//GEN-LAST:event_jb_agregaralarbolMouseClicked

    private void jb_GuardarjugadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_GuardarjugadoresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_GuardarjugadoresMouseEntered

    private void ListaEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaEquiposMouseClicked
        if (evt.isMetaDown()) {
            ListaEquipos.getSelectedValue();
            ModificarEquipos.setModal(true);
            ModificarEquipos.pack();
            ModificarEquipos.setLocationRelativeTo(this);
            ModificarEquipos.setVisible(true);
        }

    }//GEN-LAST:event_ListaEquiposMouseClicked

    private void ListaJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaJugadoresMouseClicked
        if (evt.isMetaDown()) {
            ListaJugadores.getSelectedValue();
            ModificarJugadores.setModal(true);
            ModificarJugadores.pack();
            ModificarJugadores.setLocationRelativeTo(this);
            ModificarJugadores.setVisible(true);
        }
    }//GEN-LAST:event_ListaJugadoresMouseClicked

    private void jb_modificarJugadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarJugadoresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_modificarJugadoresMouseEntered

    private void jb_modificarJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarJugadoresMouseClicked
        DefaultListModel modeloj = (DefaultListModel) ListaJugadores.getModel();
        if (rb_atacante1.isSelected()) {
            modeloj.addElement(new Jugadores(tf_nombrejmod.getText(), Integer.parseInt(tf_precio1.getText()), "Atacante", tf_Disp1.getText(), Double.parseDouble(tf_habilidad1.getText()), Double.parseDouble(tf_tecnica1.getText()), Double.parseDouble(tf_resist1.getText())));
        }
        if (rb_defensa1.isSelected()) {
            modeloj.addElement(new Jugadores(tf_nombrejmod.getText(), Integer.parseInt(tf_precio1.getText()), "Defensa", tf_Disp1.getText(), Double.parseDouble(tf_habilidad1.getText()), Double.parseDouble(tf_tecnica1.getText()), Double.parseDouble(tf_resist1.getText())));
        }
        if (rb_mediocampo1.isSelected()) {
            modeloj.addElement(new Jugadores(tf_nombrejmod.getText(), Integer.parseInt(tf_precio1.getText()), "Medio Campista", tf_Disp1.getText(), Double.parseDouble(tf_habilidad1.getText()), Double.parseDouble(tf_tecnica1.getText()), Double.parseDouble(tf_resist1.getText())));
        }
        if (rb_portero1.isSelected()) {
            modeloj.addElement(new Jugadores(tf_nombrejmod.getText(), Integer.parseInt(tf_precio1.getText()), "Portero", tf_Disp1.getText(), Double.parseDouble(tf_habilidad1.getText()), Double.parseDouble(tf_tecnica1.getText()), Double.parseDouble(tf_resist1.getText())));
        }
    }//GEN-LAST:event_jb_modificarJugadoresMouseClicked

    private void jb_ModEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ModEquiposMouseClicked
        DefaultListModel modelol = (DefaultListModel) ListaEquipos.getModel();
        modelol.addElement(new Equipos(tf_nombreequipo1.getText(), Integer.parseInt(tf_presupuesto1.getText()), Integer.parseInt(tf_copas1.getText()), tf_nombreestadio1.getText()));
        DefaultTreeModel m = (DefaultTreeModel) jt_Distrub.getModel();
        DefaultMutableTreeNode LigaEspanola = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode Equipo;
        Equipo = new DefaultMutableTreeNode(new Equipos(tf_nombreequipo1.getText(), Integer.parseInt(tf_presupuesto1.getText()), Integer.parseInt(tf_copas1.getText()), tf_nombreestadio1.getText()));
        LigaEspanola.add(Equipo);
        m.reload();

    }//GEN-LAST:event_jb_ModEquiposMouseClicked
///////////ELMINAR DE LA LISTA A LOS EQUIPOS
    private void EliminarlistadeequiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarlistadeequiposMouseClicked
        DefaultListModel m = (DefaultListModel) ListaEquipos.getModel();
        m.remove(ListaEquipos.getSelectedIndex());


    }//GEN-LAST:event_EliminarlistadeequiposMouseClicked

    private void EliminarlistadejugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarlistadejugadoresMouseClicked
        DefaultListModel m = (DefaultListModel) ListaJugadores.getModel();
        m.remove(ListaJugadores.getSelectedIndex());
    }//GEN-LAST:event_EliminarlistadejugadoresMouseClicked
//ELIMINAR COSAS
    private void jt_DistrubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_DistrubMouseClicked
        if (evt.isMetaDown()) {
            int row = jt_Distrub.getClosestRowForLocation(evt.getX(), evt.getY());
            Object c = jt_Distrub.getSelectionPath().getLastPathComponent();
            nodoselect = (DefaultMutableTreeNode) c;
            if (nodoselect.getUserObject() instanceof Jugadores) {
                jselect = (Jugadores) nodoselect.getUserObject();
                popuparbol.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_jt_DistrubMouseClicked

    private void Ver_JugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_JugadorActionPerformed
        JOptionPane.showMessageDialog(this, "nombre: " + jselect.getNombre());
        JOptionPane.showMessageDialog(this, "Precio: " + jselect.getPrecio());
        JOptionPane.showMessageDialog(this, "Posicion: " + jselect.getPos());
        JOptionPane.showMessageDialog(this, "Disponivilidad : " + jselect.getDisponibilidad());
        JOptionPane.showMessageDialog(this, "Tecnica: " + jselect.getTecnica());
        JOptionPane.showMessageDialog(this, "Habilidad: " + jselect.getHabilidad());
        JOptionPane.showMessageDialog(this, "resistencia: " + jselect.getResistencia());
    }//GEN-LAST:event_Ver_JugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liga_Espanola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liga_Espanola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liga_Espanola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liga_Espanola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liga_Espanola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agregar_Equpos;
    private javax.swing.JDialog Agregar_Jugadores;
    private javax.swing.JMenuItem Eliminar_jugador;
    private javax.swing.JButton Eliminarlistadeequipos;
    private javax.swing.JButton Eliminarlistadejugadores;
    private javax.swing.JList<Equipos> ListaEquipos;
    private javax.swing.JList<Jugadores> ListaJugadores;
    private javax.swing.JDialog ModificarEquipos;
    private javax.swing.JDialog ModificarJugadores;
    private javax.swing.JMenuItem Ver_Jugador;
    private javax.swing.ButtonGroup bg_posicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_Guardarjugadores;
    private javax.swing.JButton jb_ModEquipos;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_agregarEquipos;
    private javax.swing.JButton jb_agregaralarbol;
    private javax.swing.JButton jb_guardarEquipo;
    private javax.swing.JButton jb_modificarJugadores;
    private javax.swing.JTree jt_Distrub;
    private javax.swing.JPopupMenu popuparbol;
    private javax.swing.JRadioButton rb_atacante;
    private javax.swing.JRadioButton rb_atacante1;
    private javax.swing.JRadioButton rb_defensa;
    private javax.swing.JRadioButton rb_defensa1;
    private javax.swing.JRadioButton rb_mediocampo;
    private javax.swing.JRadioButton rb_mediocampo1;
    private javax.swing.JRadioButton rb_portero;
    private javax.swing.JRadioButton rb_portero1;
    private javax.swing.JTextField tf_Disp;
    private javax.swing.JTextField tf_Disp1;
    private javax.swing.JTextField tf_copas;
    private javax.swing.JTextField tf_copas1;
    private javax.swing.JTextField tf_habilidad;
    private javax.swing.JTextField tf_habilidad1;
    private javax.swing.JTextField tf_nombreequipo;
    private javax.swing.JTextField tf_nombreequipo1;
    private javax.swing.JTextField tf_nombreestadio;
    private javax.swing.JTextField tf_nombreestadio1;
    private javax.swing.JTextField tf_nombrej;
    private javax.swing.JTextField tf_nombrejmod;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_precio1;
    private javax.swing.JTextField tf_presupuesto;
    private javax.swing.JTextField tf_presupuesto1;
    private javax.swing.JTextField tf_resist;
    private javax.swing.JTextField tf_resist1;
    private javax.swing.JTextField tf_tecnica;
    private javax.swing.JTextField tf_tecnica1;
    // End of variables declaration//GEN-END:variables
DefaultMutableTreeNode nodoselect;
    Jugadores jselect;

}
